server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bwl?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: claudio
    password: america2010
  flyway:
    enabled: true
    baseline-version: 000
    baseline-on-migrate: true
    locations:
    - classpath:/db/migration
    table: bwl_migration
    validate-on-migrate: false
  
  jpa:
    generate-ddl: true
    show-sql: true
    
  