server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bwl?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: natasec
    password: naberius10
  
  jpa:
    generate-ddl: true
    show-sql: true